# Generated by Django 2.2.5 on 2020-03-07 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0006_auto_20200307_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='tree',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='trees.Tree'),
        ),
    ]
