# Generated by Django 2.1 on 2020-03-10 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0008_skill_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='bronzeCost',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='goldCost',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='platinumCost',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='silverCost',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
