# Generated by Django 2.2.5 on 2020-03-16 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0010_mskill'),
    ]

    operations = [
        migrations.AddField(
            model_name='mskill',
            name='bronzeCost',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='mskill',
            name='checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mskill',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='mskill',
            name='goldCost',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='mskill',
            name='platinumCost',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='mskill',
            name='silverCost',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='mskill',
            name='tree_field',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='trees.Tree'),
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
